import type { SocialPost } from '../types';
import { brand } from '../brand/tokens';
import { squabLogoData } from '../brand/logoData';
import { normaliseTemplateId } from '../templates/registry';

export type RenderSize = 'portrait' | 'square' | 'linkedin';
const sizes: Record<RenderSize, [number, number]> = { portrait: [1080,1350], square: [1080,1080], linkedin: [1200,1200] };
const C = brand.colours;
const esc = (value='') => value.replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char] || char));

function wrap(text:string, limit:number, max=5){const words=text.trim().split(/\s+/).filter(Boolean);const out:string[]=[];let line='';for(const word of words){const next=`${line} ${word}`.trim();if(next.length>limit&&line){out.push(line);line=word}else line=next}if(line)out.push(line);return out.slice(0,max)}
function textBlock(text:string,x:number,y:number,chars:number,size:number,leading:number,fill:string,weight=900,rotate=0){return `<g transform="rotate(${rotate} ${x} ${y})"><text x="${x}" y="${y}" fill="${fill}" font-family="Lato,Arial,sans-serif" font-size="${size}" font-weight="${weight}">${wrap(text,chars).map((line,i)=>`<tspan x="${x}" dy="${i?leading:0}">${esc(line)}</tspan>`).join('')}</text></g>`}
function photo(post:SocialPost,x:number,y:number,w:number,h:number,id:string,r=0){if(!post.image)return `<g><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="#2b2b2b"/><text x="${x+w/2}" y="${y+h/2}" text-anchor="middle" fill="#777" font-family="Lato" font-size="26" font-weight="900">ADD PHOTO</text></g>`;return `<defs><clipPath id="${id}"><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}"/></clipPath></defs><image href="${post.image}" x="${x}" y="${y}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid slice" clip-path="url(#${id})"/>`}
function logo(x:number,y:number,w=210){return `<image href="${squabLogoData}" x="${x}" y="${y}" width="${w}" preserveAspectRatio="xMinYMid meet"/>`}
function defs(){return `<defs><filter id="shadow"><feDropShadow dx="0" dy="18" stdDeviation="18" flood-color="#000" flood-opacity=".28"/></filter><filter id="grain"><feTurbulence type="fractalNoise" baseFrequency=".75" numOctaves="3" seed="3"/><feColorMatrix type="saturate" values="0"/><feComponentTransfer><feFuncA type="table" tableValues="0 .12"/></feComponentTransfer></filter><linearGradient id="shade" x1="0" y1="0" x2="0" y2="1"><stop offset="18%" stop-color="#000" stop-opacity=".02"/><stop offset="90%" stop-color="#000" stop-opacity=".88"/></linearGradient><linearGradient id="orange" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${C.orange}"/><stop offset="1" stop-color="${C.orangeDark}"/></linearGradient></defs>`}
function scribble(x:number,y:number,w:number){return `<path d="M${x} ${y} C${x+w*.2} ${y-12},${x+w*.38} ${y+18},${x+w*.58} ${y-6} S${x+w*.88} ${y+15},${x+w} ${y-2}" fill="none" stroke="${C.orange}" stroke-width="13" stroke-linecap="round"/>`}
function footer(W:number,H:number,pad:number){return `<rect x="0" y="${H-116}" width="${W}" height="116" fill="#fff"/>${logo(pad,H-96,185)}<text x="${W-pad}" y="${H-65}" text-anchor="end" fill="#111" font-family="Lato" font-size="15" font-weight="700">SQUAB STORAGE · BRIDGWATER</text>`}
function badges(post:SocialPost,x:number,y:number){const items=post.benefits.slice(0,3);return items.map((b,i)=>`<g transform="translate(${x} ${y+i*58})"><circle cx="15" cy="15" r="15" fill="${C.orange}"/><path d="M8 15 l5 5 l10 -12" fill="none" stroke="#111" stroke-width="4"/><text x="42" y="20" fill="#fff" font-family="Lato" font-size="19" font-weight="900">${esc(b.title || b.body)}</text></g>`).join('')}

function renderBold(post:SocialPost,W:number,H:number,pad:number){return `${photo(post,0,0,W,H,'p1')}<rect width="${W}" height="${H}" fill="url(#shade)"/><text x="${pad-20}" y="${H*.22}" fill="#fff" font-family="Lato" font-size="${Math.round(W*.18)}" font-weight="900" letter-spacing="-7">${esc((wrap(post.headline,11,1)[0]||'MORE').toUpperCase())}</text>${textBlock(wrap(post.headline,20,4).slice(1).join(' ')||post.support,pad,H*.33,18,Math.round(W*.07),Math.round(W*.07),'#fff',900,-2)}${scribble(pad,H*.52,W*.42)}${badges(post,pad,H*.63)}${footer(W,H,pad)}`}
function renderPeople(post:SocialPost,W:number,H:number,pad:number){return `<rect width="${W}" height="${H}" fill="#111"/>${photo(post,W*.42,0,W*.58,H,'p2')}<path d="M0 0 H${W*.52} L${W*.4} ${H*.76} H0Z" fill="${C.orangeSoft}"/><path d="M${pad*.6} ${H*.16} H${W*.47} L${W*.43} ${H*.63} H${pad*.9}Z" fill="#fff" filter="url(#shadow)"/>${textBlock(post.headline,pad,H*.25,18,Math.round(W*.06),Math.round(W*.065),'#111',900,-3)}${scribble(pad,H*.55,W*.28)}<text x="${pad}" y="${H*.66}" fill="#111" font-family="Lato" font-size="18" font-weight="700">REAL PEOPLE. REAL STORIES.</text>${footer(W,H,pad)}`}
function renderTransformation(post:SocialPost,W:number,H:number,pad:number){return `<rect width="${W}" height="${H}" fill="#111"/>${photo(post,0,0,W,H*.73,'p3')}<rect x="0" y="0" width="${W*.49}" height="${H*.73}" fill="#000" fill-opacity=".48"/><text x="${pad}" y="${H*.11}" fill="#fff" font-family="Lato" font-size="22" font-weight="900">BEFORE</text><text x="${W*.56}" y="${H*.11}" fill="${C.orange}" font-family="Lato" font-size="22" font-weight="900">AFTER</text><path d="M${W*.5} 0 l-28 54 l32 54 l-26 54 l36 54 l-24 54 l32 54 l-30 54 l28 54 l-25 54 l30 54 l-25 54 l31 54 V${H*.73}" fill="#fff"/><path d="M0 ${H*.67} C${W*.22} ${H*.61},${W*.41} ${H*.75},${W*.62} ${H*.68} S${W*.88} ${H*.62},${W} ${H*.7} V${H} H0Z" fill="#fff"/>${textBlock(post.headline,pad,H*.78,23,Math.round(W*.06),Math.round(W*.062),'#111')}${scribble(pad,H*.9,W*.42)}${footer(W,H,pad)}`}
function renderLocal(post:SocialPost,W:number,H:number,pad:number){return `${photo(post,0,0,W,H,'p4')}<rect width="${W}" height="${H}" fill="#06121b" fill-opacity=".35"/><rect x="${pad}" y="${H*.12}" width="${W*.74}" height="${H*.38}" fill="#fff" fill-opacity=".9" transform="rotate(-2 ${pad} ${H*.12})" filter="url(#shadow)"/>${textBlock(post.headline,pad*1.35,H*.2,19,Math.round(W*.062),Math.round(W*.065),'#111',900,-2)}${scribble(pad*1.35,H*.43,W*.38)}<g transform="translate(${pad*1.35} ${H*.55}) rotate(-2)"><rect width="${W*.48}" height="110" fill="${C.orange}"/><text x="24" y="42" fill="#111" font-family="Lato" font-size="18" font-weight="900">LOCAL PEOPLE</text><text x="24" y="72" fill="#111" font-family="Lato" font-size="18" font-weight="900">LOCAL BUSINESS</text><text x="24" y="102" fill="#111" font-family="Lato" font-size="18" font-weight="900">REAL SUPPORT</text></g>${footer(W,H,pad)}`}
function renderLifestyle(post:SocialPost,W:number,H:number,pad:number){return `${photo(post,0,0,W,H,'p5')}<rect width="${W}" height="${H}" fill="url(#shade)"/><path d="M0 0 H${W*.68} C${W*.52} ${H*.18},${W*.43} ${H*.32},${W*.28} ${H*.44} H0Z" fill="#fff" fill-opacity=".93"/>${textBlock(post.headline,pad,H*.12,17,Math.round(W*.07),Math.round(W*.069),'#111',900,-3)}${scribble(pad,H*.36,W*.34)}${footer(W,H,pad)}`}
function renderFits(post:SocialPost,W:number,H:number,pad:number){return `<rect width="${W}" height="${H}" fill="#111"/>${photo(post,W*.47,0,W*.53,H,'p6')}<rect x="0" y="0" width="${W*.52}" height="${H}" fill="#111"/>${textBlock(post.headline,pad,H*.15,13,Math.round(W*.083),Math.round(W*.079),'#fff')}${scribble(pad,H*.5,W*.32)}<g transform="translate(${pad} ${H*.58}) rotate(-2)"><rect width="${W*.35}" height="${H*.21}" fill="#fff" filter="url(#shadow)"/>${post.benefits.slice(0,3).map((b,i)=>`<text x="25" y="${46+i*54}" fill="#111" font-family="Lato" font-size="20" font-weight="900">✓ ${esc(b.title)}</text>`).join('')}</g>${footer(W,H,pad)}`}
function renderSeasonal(post:SocialPost,W:number,H:number,pad:number){return `${photo(post,0,0,W,H,'p7')}<rect width="${W}" height="${H}" fill="#2a0900" fill-opacity=".3"/><rect x="${pad}" y="${H*.14}" width="${W*.72}" height="${H*.36}" fill="#111" fill-opacity=".78" transform="rotate(-2 ${pad} ${H*.14})"/>${textBlock(post.headline,pad*1.35,H*.22,16,Math.round(W*.071),Math.round(W*.07),'#fff',900,-2)}${scribble(pad*1.35,H*.45,W*.38)}<text x="${pad}" y="${H*.7}" fill="#fff" font-family="Lato" font-size="19" font-weight="700">${esc(post.support || post.answer)}</text>${footer(W,H,pad)}`}
function renderBusiness(post:SocialPost,W:number,H:number,pad:number){return `${photo(post,0,0,W,H,'p8')}<rect width="${W}" height="${H}" fill="#000" fill-opacity=".5"/><path d="M0 0 H${W*.62} L${W*.46} ${H*.67} H0Z" fill="#111" fill-opacity=".94"/>${textBlock(post.headline,pad,H*.14,14,Math.round(W*.077),Math.round(W*.074),'#fff')}${scribble(pad,H*.44,W*.3)}${badges(post,pad,H*.53)}${footer(W,H,pad)}`}
function renderTrust(post:SocialPost,W:number,H:number,pad:number){return `${photo(post,0,0,W,H,'p9')}<rect width="${W}" height="${H}" fill="#000" fill-opacity=".42"/><rect x="${W*.67}" y="0" width="${W*.33}" height="${H}" fill="#111" fill-opacity=".92"/><rect x="${pad}" y="${H*.12}" width="12" height="${H*.48}" fill="${C.orange}"/>${textBlock(post.headline,pad*1.45,H*.18,17,Math.round(W*.063),Math.round(W*.065),'#fff')}${badges(post,W*.72,H*.2)}${footer(W,H,pad)}`}
function renderTactile(post:SocialPost,W:number,H:number,pad:number){return `<rect width="${W}" height="${H}" fill="#252525"/><rect width="${W}" height="${H}" filter="url(#grain)" opacity=".6"/><g transform="translate(${pad} ${H*.12}) rotate(-3)" filter="url(#shadow)"><path d="M0 24 L${W*.68} 0 L${W*.72} ${H*.49} L18 ${H*.53}Z" fill="#f4efe5"/>${textBlock(post.headline,34,100,16,Math.round(W*.066),Math.round(W*.069),'#111',900,-1)}${scribble(34,H*.34,W*.33)}</g><g transform="translate(${W*.48} ${H*.61}) rotate(4)"><path d="M0 0 H${W*.38} L${W*.34} ${H*.17} H18Z" fill="${C.orange}"/><text x="25" y="48" fill="#111" font-family="Lato" font-size="25" font-weight="900">SPACE CREATES</text><text x="25" y="84" fill="#111" font-family="Lato" font-size="25" font-weight="900">POSSIBILITIES.</text></g>${footer(W,H,pad)}`}
function renderMinimal(post:SocialPost,W:number,H:number,pad:number){return `<rect width="${W}" height="${H}" fill="#111"/>${photo(post,W*.58,0,W*.42,H,'p11')}<rect x="${W*.58}" y="0" width="${W*.42}" height="${H}" fill="${C.orange}" fill-opacity=".12"/>${textBlock(post.headline,pad,H*.17,13,Math.round(W*.079),Math.round(W*.077),'#fff')}<rect x="${pad}" y="${H*.5}" width="${W*.26}" height="8" fill="${C.orange}"/>${footer(W,H,pad)}`}
function renderPlayful(post:SocialPost,W:number,H:number,pad:number){return `<rect width="${W}" height="${H}" fill="#a9def9"/>${photo(post,W*.43,H*.08,W*.55,H*.68,'p12',34)}<g transform="translate(${pad} ${H*.16}) rotate(-5)" filter="url(#shadow)"><rect width="${W*.48}" height="${H*.28}" fill="#fff"/>${textBlock(post.headline,24,65,13,Math.round(W*.063),Math.round(W*.064),'#111')}</g><g transform="translate(${pad*1.3} ${H*.52}) rotate(4)"><rect width="${W*.35}" height="86" fill="${C.orange}"/><text x="20" y="55" fill="#111" font-family="Lato" font-size="31" font-weight="900">NO PROBLEM.</text></g>${footer(W,H,pad)}`}

export function renderArtworkSvg(post:SocialPost,size:RenderSize='portrait'):string{
  const [W,H]=sizes[size];const pad=Math.round(W*.062);const id=normaliseTemplateId(post.template);let body='';
  switch(id){
    case 'bold-impact': body=renderBold(post,W,H,pad); break;
    case 'real-people': body=renderPeople(post,W,H,pad); break;
    case 'transformation': body=renderTransformation(post,W,H,pad); break;
    case 'local-pride': body=renderLocal(post,W,H,pad); break;
    case 'lifestyle-freedom': body=renderLifestyle(post,W,H,pad); break;
    case 'what-fits': body=renderFits(post,W,H,pad); break;
    case 'seasonal-moment': body=renderSeasonal(post,W,H,pad); break;
    case 'business-growth': body=renderBusiness(post,W,H,pad); break;
    case 'trust-security': body=renderTrust(post,W,H,pad); break;
    case 'creative-tactile': body=renderTactile(post,W,H,pad); break;
    case 'minimal-striking': body=renderMinimal(post,W,H,pad); break;
    case 'playful-unexpected': body=renderPlayful(post,W,H,pad); break;
    default: body=renderBold(post,W,H,pad);
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">${defs()}${body}</svg>`;
}

export function svgDataUrl(svg:string):string{return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`}
export function downloadSvg(post:SocialPost,size:RenderSize='portrait'){const blob=new Blob([renderArtworkSvg(post,size)],{type:'image/svg+xml'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${post.id}-${size}.svg`;a.click();URL.revokeObjectURL(url)}
