import type { SocialPost } from '../types';
import { brand } from '../brand/tokens';
import { squabLogoData } from '../brand/logoData';
import { normaliseTemplateId, templates } from '../templates/registry';
export type RenderSize='portrait'|'square'|'linkedin';
const sizes:Record<RenderSize,[number,number]>={portrait:[1080,1350],square:[1080,1080],linkedin:[1200,1200]};
const esc=(text='')=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const wrap=(text:string,limit:number)=>{const words=text.trim().split(/\s+/),lines:string[]=[];let line='';words.forEach(word=>{const next=`${line} ${word}`.trim();if(next.length>limit&&line){lines.push(line);line=word}else line=next});if(line)lines.push(line);return lines.slice(0,5)};
function textLines(text:string,x:number,y:number,chars:number,size:number,lineHeight:number,fill:string,weight=900){return `<text x="${x}" y="${y}" fill="${fill}" font-family="Lato,Arial,sans-serif" font-size="${size}" font-weight="${weight}">${wrap(text,chars).map((line,i)=>`<tspan x="${x}" dy="${i?lineHeight:0}">${esc(line)}</tspan>`).join('')}</text>`}
function imageLayer(post:SocialPost,x:number,y:number,w:number,h:number,id:string){if(!post.image)return `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${brand.colours.grey}"/><path d="M${x+w*.12} ${y+h*.78} L${x+w*.37} ${y+h*.48} L${x+w*.52} ${y+h*.64} L${x+w*.7} ${y+h*.39} L${x+w*.9} ${y+h*.78}Z" fill="#aaa"/><text x="${x+w/2}" y="${y+h*.27}" text-anchor="middle" fill="#666" font-family="Lato,Arial,sans-serif" font-size="25" font-weight="700" letter-spacing="2">ADD PHOTO</text>`;return `<defs><clipPath id="${id}"><rect x="${x}" y="${y}" width="${w}" height="${h}"/></clipPath></defs><image href="${post.image}" x="${x}" y="${y}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid slice" clip-path="url(#${id})"/>`}
function logoLockup(x:number,y:number){return `<image href="${squabLogoData}" x="${x}" y="${y}" width="188" height="61" preserveAspectRatio="xMinYMid meet"/>`}
function benefits(post:SocialPost,x:number,y:number,w:number,fill:string){const items=post.benefits.slice(0,3);if(!items.length)return '';const cell=w/items.length;return items.map((item,i)=>`<g transform="translate(${x+i*cell} ${y})"><line x1="0" y1="0" x2="${cell-28}" y2="0" stroke="${fill}" stroke-opacity=".28"/><text x="0" y="34" fill="${fill}" font-family="Lato" font-size="21" font-weight="900">${esc(item.title)}</text>${textLines(item.body,0,65,24,15,20,fill,400)}</g>`).join('')}
function accentNumber(n:number,x:number,y:number,fill:string,opacity=.13){return `<text x="${x}" y="${y}" fill="${fill}" fill-opacity="${opacity}" font-family="Lato" font-size="210" font-weight="900" text-anchor="end">${String(n).padStart(2,'0')}</text>`}
export function renderArtworkSvg(post:SocialPost,size:RenderSize='portrait'):string{const[W,H]=sizes[size],id=normaliseTemplateId(post.template),idx=Math.max(0,templates.findIndex(t=>t.id===id)),family=Math.floor(idx/2),variant=idx%2;const orange=brand.colours.orange,deep=brand.colours.orangeDark,charcoal=brand.colours.charcoal,cream=brand.colours.orangeSoft,peach=brand.colours.orangeMid;const dark=family===2?variant===0:[1,4,5,8,9,10,11].includes(family)?variant===1:false,bg=dark?charcoal:'#fff',ink=dark?'#fff':'#111',pad=Math.round(W*.065);let body='';const photo=(x:number,y:number,w:number,h:number,n:string)=>imageLayer(post,x,y,w,h,`clip-${id}-${n}`),headline=(x:number,y:number,chars=20,s=Math.round(W*.067),colour=ink)=>textLines(post.headline,x,y,chars,s,Math.round(s*.96),colour,900),eyebrow=(x:number,y:number,colour=deep)=>`<text x="${x}" y="${y}" fill="${colour}" font-family="Lato" font-size="18" font-weight="900" letter-spacing="3">${esc(post.eyebrow.toUpperCase())}</text>`;
switch(family){
case 0:body=variant?`<rect width="${W}" height="${H}" fill="${cream}"/>${photo(pad,145,W-pad*2,H*.49,'a')}<rect x="${pad}" y="${H*.605}" width="${W-pad*2}" height="${H*.285}" fill="#fff"/><rect x="${pad*1.45}" y="${H*.655}" width="74" height="8" fill="${orange}"/>${eyebrow(pad*1.45,H*.69)}${headline(pad*1.45,H*.745,23,61,'#111')}`:`${photo(0,0,W,H,'a')}<defs><linearGradient id="shade" x1="0" y1="0" x2="0" y2="1"><stop offset="15%" stop-color="#000" stop-opacity=".03"/><stop offset="86%" stop-color="#000" stop-opacity=".84"/></linearGradient></defs><rect width="${W}" height="${H}" fill="url(#shade)"/><rect x="${pad}" y="${H*.535}" width="90" height="8" fill="${orange}"/>${eyebrow(pad,H*.585,'#fff')}${headline(pad,H*.65,19,76,'#fff')}`;break;
case 1:body=variant?`<rect width="${W*.55}" height="${H}" fill="${charcoal}"/>${photo(W*.55,0,W*.45,H,'a')}${accentNumber(idx+1,W*.51,H*.18,'#fff',.06)}<rect x="${pad}" y="150" width="76" height="8" fill="${orange}"/>${eyebrow(pad,205,orange)}${headline(pad,275,15,70,'#fff')}${textLines(post.answer,pad,H*.67,31,24,32,'#fff',400)}`:`<rect width="${W}" height="${H}" fill="#fff"/>${photo(W*.47,0,W*.53,H*.72,'a')}<rect x="${pad}" y="${H*.12}" width="${W*.5}" height="${H*.51}" fill="${cream}"/><rect x="${pad*1.45}" y="${H*.18}" width="80" height="8" fill="${deep}"/>${eyebrow(pad*1.45,H*.225)}${headline(pad*1.45,H*.3,16,67,'#111')}`;break;
case 2:body=`<rect width="${W}" height="${H}" fill="${variant?cream:charcoal}"/>${accentNumber(idx+1,W-pad,H*.22,variant?'#111':'#fff',variant?.07:.05)}<rect x="${pad}" y="${H*.17}" width="${variant?130:W*.56}" height="18" fill="${orange}"/>${eyebrow(pad,H*.13,variant?deep:orange)}${headline(pad,H*.29,variant?17:14,variant?76:92,variant?'#111':'#fff')}${textLines(post.answer,pad,H*.69,42,27,36,variant?'#333':'#fff',400)}`;break;
case 3:body=variant?`<rect width="${W}" height="${H}" fill="${cream}"/>${photo(pad,H*.105,W-pad*2,H*.385,'a')}<rect x="${pad}" y="${H*.55}" width="${W-pad*2}" height="${H*.29}" fill="#fff"/><rect x="${pad*1.45}" y="${H*.6}" width="72" height="8" fill="${orange}"/>${eyebrow(pad*1.45,H*.645)}${headline(pad*1.45,H*.705,22,59,'#111')}`:`<rect width="${W}" height="${H}" fill="#fff"/>${photo(pad,H*.1,(W-pad*2)/2-10,H*.42,'a')}${photo(W/2+10,H*.1,(W-pad*2)/2-10,H*.42,'b')}<rect x="${W/2-38}" y="${H*.105}" width="76" height="${H*.41}" fill="${orange}"/>${eyebrow(pad,H*.61)}${headline(pad,H*.68,24,60,'#111')}`;break;
case 4:body=`<rect width="${W}" height="${H}" fill="${bg}"/>${accentNumber(idx+1,W-pad,H*.18,ink,.055)}${eyebrow(pad,150,variant?orange:deep)}${headline(pad,225,22,64,ink)}${post.benefits.slice(0,3).map((b,i)=>`<g transform="translate(${pad+i*14} ${H*.49+i*150})"><rect width="${W-pad*2-i*28}" height="125" rx="12" fill="${variant?'#444':'#fff'}" stroke="${variant?'#5e5e5e':'#ddd'}"/><rect width="7" height="125" rx="4" fill="${orange}"/><text x="30" y="43" fill="${ink}" font-family="Lato" font-size="22" font-weight="900">${esc(b.title)}</text>${textLines(b.body,30,76,46,17,22,ink,400)}</g>`).join('')}`;break;
case 5:body=variant?`<rect width="${W}" height="${H}" fill="${charcoal}"/>${photo(W*.6,0,W*.4,H,'a')}<rect x="${pad}" y="135" width="72" height="8" fill="${orange}"/>${eyebrow(pad,185,orange)}${headline(pad,255,14,64,'#fff')}${benefits(post,pad,H*.57,W*.49,'#fff')}`:`<rect width="${W}" height="${H}" fill="#fff"/>${accentNumber(3,W-pad,H*.25,orange,.12)}${eyebrow(pad,150)}${headline(pad,230,21,65,'#111')}${benefits(post,pad,H*.56,W-pad*2,'#111')}`;break;
case 6:body=variant?`<rect width="${W}" height="${H}" fill="${cream}"/>${photo(pad,130,W*.38,H*.66,'a')}<rect x="${W*.38}" y="${H*.24}" width="${W*.54}" height="${H*.48}" fill="#fff"/><text x="${W*.43}" y="${H*.31}" fill="${orange}" font-family="Lato" font-size="96" font-weight="900">“</text>${eyebrow(W*.43,H*.38)}${headline(W*.43,H*.45,15,57,'#111')}${textLines(post.answer,W*.43,H*.68,29,22,29,'#333',400)}`:`<rect width="${W}" height="${H}" fill="#fff"/><text x="${pad}" y="${H*.24}" fill="${orange}" font-family="Lato" font-size="150" font-weight="900">“</text>${headline(pad,H*.39,22,62,'#111')}${textLines(post.answer,pad,H*.66,45,23,31,'#555',400)}<rect x="${pad}" y="${H*.82}" width="160" height="8" fill="${orange}"/>`;break;
case 7:body=`<rect width="${W}" height="${H}" fill="${variant?cream:'#fff'}"/>${variant?photo(W*.64,0,W*.36,H,'a'):''}${eyebrow(pad,150)}${headline(pad,225,variant?15:22,60,'#111')}${post.benefits.slice(0,3).map((b,i)=>`<g transform="translate(${pad} ${H*.48+i*135})"><circle cx="35" cy="35" r="35" fill="${orange}"/><text x="35" y="45" text-anchor="middle" fill="#111" font-family="Lato" font-size="26" font-weight="900">${i+1}</text><text x="95" y="28" fill="#111" font-family="Lato" font-size="22" font-weight="900">${esc(b.title)}</text>${textLines(b.body,95,60,variant?24:42,17,22,'#444',400)}${i<2?`<line x1="35" y1="75" x2="35" y2="120" stroke="${deep}" stroke-width="3" stroke-opacity=".35"/>`:''}</g>`).join('')}`;break;
case 8:body=variant?`<rect width="${W}" height="${H}" fill="${charcoal}"/>${photo(0,0,W,H*.48,'a')}<rect x="${pad}" y="${H*.4}" width="${W-pad*2}" height="${H*.43}" fill="${charcoal}"/><rect x="${pad*1.4}" y="${H*.455}" width="86" height="8" fill="${orange}"/>${eyebrow(pad*1.4,H*.5,orange)}${headline(pad*1.4,H*.575,20,65,'#fff')}${textLines(post.answer,pad*1.4,H*.79,38,21,28,'#fff',400)}`:`<rect width="${W}" height="${H}" fill="#fff"/>${photo(0,0,W*.52,H,'a')}<rect x="${W*.47}" y="${H*.16}" width="${W*.47}" height="${H*.6}" fill="${cream}"/><rect x="${W*.53}" y="${H*.22}" width="74" height="8" fill="${orange}"/>${eyebrow(W*.53,H*.265)}${headline(W*.53,H*.34,14,58,'#111')}`;break;
case 9:body=variant?`<rect width="${W}" height="${H}" fill="${charcoal}"/><rect x="${pad}" y="${H*.14}" width="${W-pad*2}" height="8" fill="${orange}"/>${accentNumber(idx+1,W-pad,H*.26,'#fff',.05)}${eyebrow(pad,H*.22,orange)}${headline(pad,H*.31,19,70,'#fff')}${textLines(post.answer,pad,H*.58,39,26,35,'#fff',400)}${benefits(post,pad,H*.75,W-pad*2,'#fff')}`:`<rect width="${W}" height="${H}" fill="#fff"/><rect x="${pad}" y="${H*.14}" width="${W-pad*2}" height="8" fill="${orange}"/>${accentNumber(idx+1,W-pad,H*.27,orange,.1)}${eyebrow(pad,H*.22,deep)}${headline(pad,H*.31,19,70,'#111')}${textLines(post.answer,pad,H*.58,39,26,35,'#333',400)}${benefits(post,pad,H*.75,W-pad*2,'#111')}`;break;
case 10:body=variant?`<rect width="${W}" height="${H}" fill="${charcoal}"/><rect x="${pad}" y="${H*.14}" width="${W-pad*2}" height="${H*.64}" fill="${deep}"/>${accentNumber(idx+1,W-pad*1.5,H*.28,'#fff',.07)}${eyebrow(pad*1.5,H*.23,'#fff')}${headline(pad*1.5,H*.32,18,72,'#fff')}${textLines(post.answer,pad*1.5,H*.63,38,25,34,'#fff',400)}`:`<rect width="${W}" height="${H}" fill="#fff"/>${photo(0,0,W,H*.52,'a')}<rect x="${pad}" y="${H*.43}" width="${W-pad*2}" height="${H*.38}" fill="${cream}"/><rect x="${pad*1.4}" y="${H*.485}" width="84" height="8" fill="${orange}"/>${eyebrow(pad*1.4,H*.535)}${headline(pad*1.4,H*.61,20,63,'#111')}`;break;
default:body=variant?`<rect width="${W}" height="${H}" fill="${charcoal}"/>${photo(W*.55,0,W*.45,H,'a')}<rect x="${pad}" y="${H*.16}" width="${W*.52}" height="${H*.56}" fill="${peach}"/><rect x="${pad*1.35}" y="${H*.22}" width="78" height="8" fill="${deep}"/>${eyebrow(pad*1.35,H*.265,deep)}${headline(pad*1.35,H*.345,16,60,'#111')}`:`<rect width="${W}" height="${H}" fill="#fff"/>${photo(pad,110,W-pad*2,H*.48,'a')}<rect x="${pad}" y="${H*.615}" width="82" height="8" fill="${orange}"/>${eyebrow(pad,H*.66)}${headline(pad,H*.73,22,62,'#111')}`}
return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">${body}<rect x="0" y="${H-120}" width="${W}" height="120" fill="#fff"/>${logoLockup(pad,H-91)}<text x="${W-pad}" y="${H-72}" text-anchor="end" fill="#111" font-family="Lato" font-size="18" font-weight="700">${esc(post.footerTitle)}</text><text x="${W-pad}" y="${H-44}" text-anchor="end" fill="#555" font-family="Lato" font-size="14">${esc(post.footerLine)}</text></svg>`}
export function svgDataUrl(svg:string){return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`}
